### ISSUE TITLE
sentimentAnalysis授权无效

### ISSUE THREAD

**Issue by xystcz** [NLPIR-team/NLPIR#1]
在eclipse中导入“NLPIR SDK\SentimentAnalysis\project\SentimentAnalysis_java”目录下的工程后运行提示初始化失败，error文件中显示“License file sentimentAnalysisData\Data\sentiment.user can not open!”
使用license文件夹下的授权文件替换后仍有此错误。
授权文件可能存在问题。

**Comment by huoshan12345** [comment]
把data文件夹放到工程的根目录下，然后替换新授权
一般这个错误是因为初始化的时候data文件夹的目录不正确，导致授权文件找不到

**Comment by hellodcj** [comment]
我也遇到这个问题了。用ICTCLAS2015文件夹的Data覆盖后，出现初始化失败：License file DocExtractor.user can not open!

**Comment by xystcz** [comment]
这个不是Data目录错误的问题，使用当前版的sentiment.user本提示““License file sentimentAnalysisData\Data\sentiment.user can not open!””，使用历史版本中的sentiment.user则提示授权过期。@huoshan12345

**Comment by huoshan12345** [comment]
@xystcz 
授权已经更新，请下载新的授权

**Comment by yanggeorge** [comment]
@huoshan12345 情感分析的授权文件过期了，有最新的授权文件么?我在大数据论坛找到了一个7天的sentiment的授权，但是已经过期了。
