### ISSUE TITLE
是否还会继续提供一个月版的免费许可文件呢？

### ISSUE THREAD

**Issue by PhanTask** [NLPIR-team/NLPIR#10]
今天初始化挂了，来github下载新的许可，发现只上传了7天版的，官网也没有更新，请问是否还会继续提供一个月版的免费许可文件？

**Comment by Dr-Kevin-Zhang** [comment]
https://github.com/NLPIR-team/NLPIR/tree/master/License/license%20for%20a%20month/NLPIR-ICTCLAS分词系统授权 6月30日到期



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： PhanTask
发送时间： 2016-04-04 23:29
收件人： NLPIR-team/NLPIR
主题： [NLPIR-team/NLPIR] 是否还会继续提供一个月版的免费许可文件呢？ (#10)
今天初始化挂了，来github下载新的许可，发现只上传了7天版的，官网也没有更新，请问是否还会继续提供一个月版的免费许可文件？
