### ISSUE TITLE
请问是否有停用词功能？

### ISSUE THREAD

**Issue by yuanlily** [NLPIR-team/NLPIR#109]
提取的关键词中包含了一些我不需要的词，请问是否有接口能够设定这些词不要出现在结果中，我用DelUsrWord 发现不行

**Comment by phylieac** [comment]
提供了黑名单功能，importblacklist倒入黑名单词列表

发自我的 iPhone

在 2018年3月7日，下午3:28，LL <notifications@github.com<mailto:notifications@github.com>> 写道：


提取的关键词中包含了一些我不需要的词，请问是否有接口能够设定这些词不要出现在结果中，我用DelUsrWord 发现不行
