### ISSUE TITLE
授权换成新的之后起不来，java(tm) platform se binary

### ISSUE THREAD

**Issue by symfighting** [NLPIR-team/NLPIR#113]
换成新的之后怎么都起不来，请问有人知道什么原因吗？
![image](https://user-images.githubusercontent.com/30884593/37198355-0163a368-23b9-11e8-9293-aa2d3406f88c.png)

**Comment by SuperUNITE** [comment]
我在想，是不是官方的维护人员错传了旧版本的License文件？

**Comment by symfighting** [comment]
难道除了我就没有别人碰到这个问题了？？？奇怪
