### ISSUE TITLE
文旦摘要组件的License过期问题，测试应用，急！～谢谢

### ISSUE THREAD

**Issue by SuperUNITE** [NLPIR-team/NLPIR#114]
我在测试您这边的开源项目，其中，Summary组件，更新了最新的License依然报如下错误，请查看问题：

Not valid license or your license expired! Please feel free to contact the author! path=/NLPIR/NLPIR SDK/Summary/Data/summary.user

该user文件从License/license of one month下拷贝而来，依然是不行的。

**Comment by SuperUNITE** [comment]
不知道这样的响应机制能不能及时找到解决方案？

**Comment by SuperUNITE** [comment]
Not valid license or your license expired! Please feel free to contact the author! path=/home/projects/nlpir/Data//DeepClassifier/deepclassifier.user

我是不是哪里搞错了，怎么都不行呢

**Comment by phylieac** [comment]
最新的月授权，会在https://github.com/NLPIR-team/NLPIR/tree/master/License/license%20for%20a%20month提供

**Comment by phylieac** [comment]
可能git更新导致授权文件不一直，售后会更新

**Comment by phylieac** [comment]
新授权已经更新
