### ISSUE TITLE
求解答有关Fatal Error! Can not open License file  .user

### ISSUE THREAD

**Issue by MengyingQian** [NLPIR-team/NLPIR#117]
Fatal Error! Can not open License file D:\work\workspace\Test\Data\deepclassifier.user
这个好像不是过期造成的，过期报错应该是Not valid license or your license expired!
查了.user文件是4k的正常版也是最新的。
请问这种情况之前是否出现过，在什么情况下会出这个报错，如何解决呢？

补充一下用的是java版

**Comment by Dr-Kevin-Zhang** [comment]
更新即可



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts

 
发件人： MengyingQian
发送时间： 2018-03-12 18:40
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] 求解答有关Fatal Error! Can not open License file .user (#117)
Fatal Error! Can not open License file D:\work\workspace\Test\Data\deepclassifier.user
这个好像不是过期造成的，过期报错应该是Not valid license or your license expired!
查了.user文件是4k的正常版也是最新的。
请问这种情况之前是否出现过，在什么情况下会出这个报错，如何解决呢？

**Comment by MengyingQian** [comment]
所有程序都已经是最新版的了

**Comment by phylieac** [comment]
更新最新的.user授权，可能是授权损坏

**Comment by MengyingQian** [comment]
刚刚尝试了一下使用parser平台，报错显示nlpir.user的授权有问题，翻前面的评论说是要对应功能的.user文件和nlpir.user文件同时起作用，github上的更新情况显示包含nlpir.user的Data文件夹最近更新时间都在三个月之前，只有功能更新是最近几天，不知道是不是有什么关系？

已经尝试了删库重新clone，依旧失败

**Comment by yuanlily** [comment]
我也遇到了这个问题，在license文件夹里下载新的授权文件把Data里的替换掉就好了，Data里面的文件不是最新的

**Comment by MengyingQian** [comment]
经过楼上提醒，发现了nlpir.user文件在分词文件夹后，将其拷贝出来和各个功能对应的user文件一起使用，可是只有sentiment功能使用正常，其它功能依然初始化失败。不知道什么原因。
