### ISSUE TITLE
DocExtractor 自定义词

### ISSUE THREAD

**Issue by yuanlily** [NLPIR-team/NLPIR#119]
请问DocExtractor 中 DE_ParseDocE()中 的参数“用户自定义词性标记”，是否需要提前加入自定义词典中并在词典里添加一些例词？

**Comment by phylieac** [comment]
如果确实使用到了自定的实体，需要再用户词性中指定相应实体的标记，在DE_ParseDocE()中处理时，叫自定义标记传入，并按顺序值，获取相应的实体抽取结果，如果不需要用户词，则可以不引入词性和对相应参数处理。

**Comment by Dr-Kevin-Zhang** [comment]
对的。除非你定义已经有的词汇。



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts

 
发件人： LL
发送时间： 2018-03-13 18:00
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] DocExtractor 自定义词 (#119)
请问DocExtractor 中 DE_ParseDocE()中 的参数“用户自定义词性标记”，是否需要提前加入自定义词典中并在词典里添加一些例词？
