### ISSUE TITLE
PYNLPIR.open()报错

### ISSUE THREAD

**Issue by hzh1-cl** [NLPIR-team/NLPIR#128]
![1524024407131](https://user-images.githubusercontent.com/33189178/38911412-2c073e9c-429d-11e8-9a24-c9161e99585f.jpg)

如图示，我用python3，运行 pynlpir update 报错说 cannot fetch the newest license

我已经装了最新的版本了 0.5.2. 

请问是什么问题？
谢谢！

**Comment by Dr-Kevin-Zhang** [comment]
替换最新的授权文件吧。 https://github.com/NLPIR-team/NLPIR



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts

 
发件人： laurentzz
发送时间： 2018-04-18 12:13
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] PYNLPIR.open()报错 (#128)
如图示，我用python3，运行 pynlpir update 报错说 cannot fetch the newest license
我已经装了最新的版本了 0.5.2.
请问是什么问题？
谢谢！
―

**Comment by laurentzz** [comment]
![1524026137166](https://user-images.githubusercontent.com/33189178/38911943-a4d482c8-42a0-11e8-81ef-5b8629c62e01.jpg)
更新之后又出现了新的问题。。。
😓
