### ISSUE TITLE
在linux下运行提示 Not valid license or your license expired! Please feel free to contact the author! path=/Data/sentiment.user

### ISSUE THREAD

**Issue by liuyu5337** [NLPIR-team/NLPIR#133]
在windows7下编译运行没有问题，将windows下的程序部署到linux后，提示
Not valid license or your license expired! Please feel free to contact the author! path=/Data/sentiment.user.
linux下的授权文件和windows是一致的。请问这是为什么？

**Comment by Dr-Kevin-Zhang** [comment]
_Init函数初始化路径的问题



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信公众号：大数据千人会
GitHub：https://github.com/NLPIR-team/NLPIR

Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Subscriptions: Thousands of  Big Data Experts
GitHub：https://github.com/NLPIR-team/NLPIR

 
发件人： liuyu5337
发送时间： 2018-05-22 11:17
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] 在linux下运行提示 Not valid license or your license expired! Please feel free to contact the author! path=/Data/sentiment.user (#133)
在windows7下编译运行没有问题，将windows下的程序部署到linux后，提示
Not valid license or your license expired! Please feel free to contact the author! path=/Data/sentiment.user.
linux下的授权文件和windows是一致的。请问这是为什么？

**Comment by liuyu5337** [comment]
@Dr-Kevin-Zhang  ，麻烦张老师详细讲一下，路径有什么问题，这这个路径下有对应的授权文件。而且我在初始化函数里_Init里也指明了/Data的路径。为什么在linux下就会报这个错误呢？

**Comment by liuyu5337** [comment]
@lingjoin-luofang ， @Dr-Kevin-Zhang 请问使用关键词抽取模块在linux 下运行没有问题，为什么SentimentNew模块就有这个问题呢？该如何解决路径问题？我已经在CLibrarySentiment.Instance.ST_Init(DataPath, 1, "") 指定DataPath了。

**Comment by liuyu5337** [comment]
问题已解决。感谢灵玖软件朱勇的帮助。是授权文件的问题。如果SentimentNew.user 的MD5 是 "5453c6bb73b5ecd04ca6215657adca29" 则这个 user文件是有问题的，在linux下无法运行。我更新之后新的SentimentNew.user的md5是"d90cfe7a496b72313ff4a370e31aac11"，这个user文件是可以的。有问题的同学记得更新user文件。
