### ISSUE TITLE
请问这次的授权更新是否已经更新完整，覆盖Data之后依然初始化失败，之前是可以用的

### ISSUE THREAD

**Issue by MengyingQian** [NLPIR-team/NLPIR#141]

**Comment by Dr-Kevin-Zhang** [comment]
更新完整，具体是哪个功能有问题？



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信公众号：大数据千人会
GitHub：https://github.com/NLPIR-team/NLPIR

Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Subscriptions: Thousands of  Big Data Experts
GitHub：https://github.com/NLPIR-team/NLPIR

 
发件人： MengyingQian
发送时间： 2018-06-22 11:55
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] 请问这次的授权更新是否已经更新完整，覆盖Data之后依然初始化失败，之前是可以用的 (#141)

**Comment by MengyingQian** [comment]
SentimentAnalysis_java  我直接把更新的License文件夹里面的16个.user文件拷贝出来粘到了java工程的Data文件夹并进行了覆盖，这样的操作是正确的吗？我只用了两个月，记得上一次也是这么操作的
