### ISSUE TITLE
建议更新下 mac 下的动态库

### ISSUE THREAD

**Issue by liudongmiao** [NLPIR-team/NLPIR#15]
张教授您好，目前`mac`下的动态库在 `ios` 目录下，而且，`id` 很古怪。

```
DeepClassifier/lib/ios/libDeepClassifier.so:
    ../../../bin/Classifier/libDeepClassifier.so (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
DocExtractor/lib/ios/libDocExtractor.so:
    ../../../bin/DocExtractor/libDocExtractor.so (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
NLPIR-ICTCLAS/lib/ios/libNLPIR.so:
    ../../../bin/ICTCLAS/libNLPIR.so (compatibility version 0.0.0, current version 0.0.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

一来，目录应该叫 `darwin` 比较合适 (参照`jna`叫法)，或者叫 `macosx` 也可以啊；同时，文件名，在`mac`下一般是 `.dylib`，虽然`.so`也能认。
二来，在编译链接的时候，找这个目录也很困难。您可以在编译的时候处理，也可以在现在的基础上处理。可以使用命令 `install_name_tool -id <name> <lib>` 来指定，如`install_name_tool -id libNLPIR.so NLPIR-ICTCLAS/lib/ios/libNLPIR.so`.

**Comment by smilepy** [comment]
你好，mac下运行NLPIR-ICTCLAS里的java版本NlpirTest.java程序，总是报错：java.lang.UnsatisfiedLinkError: Unable to load library 'linux32/NLPIR.so': Native library (darwin/liblinux32/NLPIR.so.dylib) not found in resource path。
应该如何配置LD_LIBRARY_PATH环境变量啊？我这设置为LD_LIBRARY_PATH=“/Users/smilepy/ws/java/NLPIR/NLPIR SDK/NLPIR-ICTCLAS/lib/ios”

**Comment by phylieac** [comment]
https://github.com/NLPIR-team/NLPIR-ICTCLAS

**Comment by smilepy** [comment]
@phylieac    在项目https://github.com/NLPIR-team/NLPIR-ICTCLAS中，编译NLPIRTest.java
文件时还是报错。
AT3706:test smilepy$ javac NLPIRTest.java
NLPIRTest.java:9: 错误: 找不到符号
import com.lingjoin.nlpir.NLPIR;
                         ^
  符号:   类 NLPIR
  位置: 程序包 com.lingjoin.nlpir

**Comment by phylieac** [comment]
@smilepy 导入Eclipse中，使用工程，javac编译单个.java无法找到引用

**Comment by smilepy** [comment]
@phylieac   我是导入idea中，通过右键run NLPIRTest.java文件依然报错。
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'NLPIR': Native library (darwin/libNLPIR.dylib) not found in resource path     这个具体是动态库的配置问题吧，具体怎么配置啊，已经试了好多办法了，但一直没找到问题的点上。

**Comment by phylieac** [comment]
把工程下resources目录转为idea下的resource目录

**Comment by smilepy** [comment]
@phylieac 谢谢你的帮助，问题解决了，也明白了其加载动态库的原理

**Comment by rtspVideoview** [comment]
在mac系统下的eclipse中导入https://github.com/NLPIR-team/NLPIR-ICTCLAS下的项目总是报错Unable to load library 'NLPIR': Native library (darwin/libNLPIR.dylib) not found in resource path ([file:/Users/ldy/Downloads/NLPIR-ICTCLAS-master/build/classes/, file:/Users/ldy/Downloads/NLPIR-ICTCLAS-master/lib/jna-4.1.0.jar])，请问如何解决 @phylieac

**Comment by phylieac** [comment]
把resources目录，在buildpath中改为use as source folder

**Comment by smilepy** [comment]
得更改下引用的动态文件，到公司了我详细说下




在2017年03月24日 12:06，Hongyan Pan 写道：

把resources目录，在buildpath中改为use as source folder

**Comment by rtspVideoview** [comment]
@smilepy @phylieac 谢谢你们的帮助，问题已经解决了
