### ISSUE TITLE
NLPIR SDK\SentimentAnalysis中授权匹配及demo不可用

### ISSUE THREAD

**Issue by endcy** [NLPIR-team/NLPIR#159]
选型测试卡住了，SentimentAnalysis和SentimentNew使用的相同Sentiment.user，NLPIR SDK\SentimentNew\projects\SentimentNew_java在替换授权文件及dll之后，此demo可以正常运行，但是NLPIR SDK\SentimentAnalysis\project\SentimentAnalysis_java的demo无论如何更新替换，都无法正常运行，此java demo中的文件，如果dll不替换为\NLPIR SDK\SentimentAnalysis\lib\中的文件，那么提示授权文件打不开，如果替换掉，则又提示授权失效过期请更新（该情况下sentiment.user和NLPIR.user已经替换更新）。所以，此处是否漏掉了部分更新？还望解答，万分感谢！

**Comment by Chandler-Song** [comment]
C:\Users\HP\Desktop\NLPIR-Parser\bin-win64  我打开这个目录下的NLPIR-Parser.exe，显示图片如下，这个应该怎么解决？
![image](https://user-images.githubusercontent.com/23094571/58076497-efefc300-7bdc-11e9-9836-cbc653a91f7e.png)
