### ISSUE TITLE
libLJSentimentAnalysis情感分析返回结果都是0

### ISSUE THREAD

**Issue by MarcoQin** [NLPIR-team/NLPIR#18]
使用linux64下的.so文件，无论输入什么，输出都是如下：
EMOTION_HAPPY/0
EMOTION_GOOD/0
EMOTION_ANGER/0
EMOTION_SORROW/0
EMOTION_FEAR/0
EMOTION_EVIL/0
EMOTION_SURPRISE/0

请教一下是不是我的使用姿势有问题= =！

**Comment by Dr-Kevin-Zhang** [comment]
词典没有更新，可以替换成Github最新版本的 data  https://github.com/NLPIR-team/NLPIR/tree/master/NLPIR%20SDK/SentimentAnalysis/Data 



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： MarcoQin
发送时间： 2016-06-08 15:36
收件人： NLPIR-team/NLPIR
主题： [NLPIR-team/NLPIR] libLJSentimentAnalysis情感分析返回结果都是0 (#18)
使用linux64下的.so文件，无论输入什么，输出都是如下：
EMOTION_HAPPY/0
EMOTION_GOOD/0
EMOTION_ANGER/0
EMOTION_SORROW/0
EMOTION_FEAR/0
EMOTION_EVIL/0
EMOTION_SURPRISE/0
请教一下是不是我的使用姿势有问题= =！

**Comment by MarcoQin** [comment]
好的谢谢！
