### ISSUE TITLE
过期了，急用调试

### ISSUE THREAD

**Issue by wanqql** [NLPIR-team/NLPIR#180]
今天刚好一个月结束，急着调试

**Comment by hwhot** [comment]
好像不能用了，什么时候可以用呀

**Comment by hwhot** [comment]
License/license for a month/NLPIR-Parser平台授权/NLPIRParser.user

这个文件一直没更新吗，下载下来不能用

**Comment by jyja** [comment]
什么时候更新呀，调试急用

**Comment by Dr-Kevin-Zhang** [comment]
并没有过期啊，访问 https://github.com/NLPIR-team/NLPIR/tree/master/License/license%20for%20a%20month 下载替换。



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信公众号：大数据千人会
GitHub：https://github.com/NLPIR-team/NLPIR

Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Subscriptions: Thousands of  Big Data Experts
GitHub：https://github.com/NLPIR-team/NLPIR

 
发件人： jyja
发送时间： 2020-02-11 11:36
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： Re: [NLPIR-team/NLPIR] 过期了，急用调试 (#180)
什么时候更新呀，调试急用

**Comment by jyja** [comment]
已重新替换，还是显示过期了



---原始邮件---
发件人: "Dr. Kevin Zhang"<notifications@github.com&gt;
发送时间: 2020年2月11日(周二) 下午5:23
收件人: "NLPIR-team/NLPIR"<NLPIR@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"jyja"<1225028490@qq.com&gt;;
主题: Re: [NLPIR-team/NLPIR] 过期了，急用调试 (#180)


并没有过期啊，访问 https://github.com/NLPIR-team/NLPIR/tree/master/License/license%20for%20a%20month 下载替换。 
 
 
 
 Best wishes 
 张华平 博士 副教授 研究生导师 
 大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任 
 地址：北京海淀区中关村南大街5号 100081 
 电话：+86-10-68918642 
 Email:kevinzhang@bit.edu.cn 
 MSN:  pipy_zhang@msn.com; 
 网站: http://www.nlpir.org (自然语言处理与信息检索共享平台) 
 http://www.bigdataBBS.com (大数据论坛) 
 微博:http://www.weibo.com/drkevinzhang/ 
 微信公众号：大数据千人会 
 GitHub：https://github.com/NLPIR-team/NLPIR 
 
 Dr. Kevin Zhang  (张华平，Zhang Hua-Ping) 
 Associate Professor, Graduate Supervisor 
 Director, Big Data Search and Mining Lab.  
 Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application 
 Beijing Institute of Technology 
 Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081 
 Tel: +86-10-68918642 
 Email:kevinzhang@bit.edu.cn 
 MSN:  pipy_zhang@msn.com; 
 Website: http://www.nlpir.org (Natural Language Processing and 
 Information Retrieval Sharing Platform) 
 http://www.bigdataBBS.com (Big Data Forum) 
 Twitter: http://www.weibo.com/drkevinzhang/ 
 Subscriptions: Thousands of  Big Data Experts 
 GitHub：https://github.com/NLPIR-team/NLPIR 
 
   
 发件人： jyja 
 发送时间： 2020-02-11 11:36 
 收件人： NLPIR-team/NLPIR 
 抄送： Subscribed 
 主题： Re: [NLPIR-team/NLPIR] 过期了，急用调试 (#180) 
 什么时候更新呀，调试急用

**Comment by Dr-Kevin-Zhang** [comment]
再替换看看？



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信公众号：大数据千人会
GitHub：https://github.com/NLPIR-team/NLPIR

Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Subscriptions: Thousands of  Big Data Experts
GitHub：https://github.com/NLPIR-team/NLPIR

 
发件人： jyja
发送时间： 2020-02-11 18:22
收件人： NLPIR-team/NLPIR
抄送： Dr. Kevin Zhang; Comment
主题： Re: [NLPIR-team/NLPIR] 过期了，急用调试 (#180)
已重新替换，还是显示过期了 



---原始邮件--- 
发件人: "Dr. Kevin Zhang"<notifications@github.com&gt; 
发送时间: 2020年2月11日(周二) 下午5:23 
收件人: "NLPIR-team/NLPIR"<NLPIR@noreply.github.com&gt;; 
抄送: "Comment"<comment@noreply.github.com&gt;;"jyja"<1225028490@qq.com&gt;; 
主题: Re: [NLPIR-team/NLPIR] 过期了，急用调试 (#180) 


并没有过期啊，访问 https://github.com/NLPIR-team/NLPIR/tree/master/License/license%20for%20a%20month 下载替换。 



Best wishes 
张华平 博士 副教授 研究生导师 
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任 
地址：北京海淀区中关村南大街5号 100081 
电话：+86-10-68918642 
Email:kevinzhang@bit.edu.cn 
MSN: pipy_zhang@msn.com; 
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台) 
http://www.bigdataBBS.com (大数据论坛) 
微博:http://www.weibo.com/drkevinzhang/ 
微信公众号：大数据千人会 
GitHub：https://github.com/NLPIR-team/NLPIR 

Dr. Kevin Zhang (张华平，Zhang Hua-Ping) 
Associate Professor, Graduate Supervisor 
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application 
Beijing Institute of Technology 
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C PC:100081 
Tel: +86-10-68918642 
Email:kevinzhang@bit.edu.cn 
MSN: pipy_zhang@msn.com; 
Website: http://www.nlpir.org (Natural Language Processing and 
Information Retrieval Sharing Platform) 
http://www.bigdataBBS.com (Big Data Forum) 
Twitter: http://www.weibo.com/drkevinzhang/ 
Subscriptions: Thousands of Big Data Experts 
GitHub：https://github.com/NLPIR-team/NLPIR 


发件人： jyja 
发送时间： 2020-02-11 11:36 
收件人： NLPIR-team/NLPIR 
抄送： Subscribed 
主题： Re: [NLPIR-team/NLPIR] 过期了，急用调试 (#180) 
什么时候更新呀，调试急用
