### ISSUE TITLE
Not valid license or your license expired!

### ISSUE THREAD

**Issue by xing520tang** [NLPIR-team/NLPIR#186]
博士，情感分析组件的授权文件是不是过期了？麻烦您看一下

**Comment by jiangxue0210** [comment]
> 博士，情感分析组件的授权文件是不是过期了？麻烦您看一下

请问问题解决了吗？同显示授权非法，但我下载的是最新的license文件

**Comment by xing520tang** [comment]
> > 博士，情感分析组件的授权文件是不是过期了？麻烦您看一下
> 
> 请问问题解决了吗？同显示授权非法，但我下载的是最新的license文件

并木有

**Comment by geekWastelands** [comment]
昨天更新了
