### ISSUE TITLE
关于NLPIR SDK中的sentiment情感组件

### ISSUE THREAD

**Issue by songboyu** [NLPIR-team/NLPIR#2]
张老师您好！

最近在使用您的NLPIR SDK做一些小系统，感觉棒极了！
由于服务器使用的是linux环境，一直使用的都是.so的库文件
但是我发现这个文件夹下
NLPIR\NLPIR SDK\Sentiment\lib
并没有提供对应的linux版本
请问您能提供一下吗？谢谢您啦！

还有就是我把授权文件复制到Data文件夹下之后，还是提示
License file DocExtractor.user can not open!
该怎么办解决呢？

**Comment by huoshan12345** [comment]
已经更新了，情感分析组件不再需要DocExtractor.user了
情感分析组件还没有移植到linux平台，可能要等一段时间了

**Comment by songboyu** [comment]
好的 非常感谢

**Comment by songboyu** [comment]
License file xxx can not open!
这个是不是授权到期了啊？别的也是这样

**Comment by huoshan12345** [comment]
这个错误一般是data文件夹路径错误导致的。
如果是授权过期的话，日志会提示Not valid license or your license expired!
