### ISSUE TITLE
使用KeyScanner初始化报错

### ISSUE THREAD

**Issue by flagcugb** [NLPIR-team/NLPIR#200]
我参考了 NLPIR/NLPIR SDK/KeyScanner/doc/九眼智能过滤系统开发手册2017版.pdf 文档中4.1的例子，调用 KS_Init报错了。代码如下:
![image](https://user-images.githubusercontent.com/6836432/105972283-6d641a00-60c6-11eb-9966-c429e4df7b67.png)
错误提示如下:
![image](https://user-images.githubusercontent.com/6836432/105972454-984e6e00-60c6-11eb-9778-57070b212bf7.png)
请问老师，KeyScanner 下为什么没有 FieldDict.pdat 和 FieldDict.pos 这两个文件呢。我看了一下其他的sdk（比如NLPIR-ICTCLAS）是有这两个文件的，但我发现每个sdk的这两个文件的大小都不一样，我猜是不可以共用的，事实上，我把 NLPIR-ICTLAS/data/目录下的 FiledDict.pdata 和 FiledDict.pos 这两个文件拷到KeyScanner来，发现并不能使用。那么，我应该在哪里找这两个文件呢？

谢谢老师！

**Comment by yangyaofei** [comment]
应该是可以的, 或者可以直接使用 https://github.com/NLPIR-team/nlpir-python 或者从这个里面拷贝对应的你想要的文件

**Comment by flagcugb** [comment]
> 应该是可以的, 或者可以直接使用 https://github.com/NLPIR-team/nlpir-python 或者从这个里面拷贝对应的你想要的文件

谢谢回答。我从你说的https://github.com/NLPIR-team/nlpir-python/nlpir/Data/ 目录下拷了FiledDict.pdata 和 FiledDict.pos 两个文件过来用，不报 "Cannot open filed dicttionary"的错误了。但报了一下错误，是怎么回事呢，有点想不明白。
![image](https://user-images.githubusercontent.com/6836432/106099145-2bde7800-6175-11eb-9dee-317fa18f086c.png)

**Comment by yangyaofei** [comment]
你传入的参数应该存在问题,请仔细阅读对应头文件
