### ISSUE TITLE
请问NLPIR 授权请求服务器的端口是多少？

### ISSUE THREAD

**Issue by xifengy** [NLPIR-team/NLPIR#201]
已解决

**Comment by Dr-Kevin-Zhang** [comment]
可以改为内部客户端工具注册，在licenseClient




Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信公众号：大数据千人会
GitHub：https://github.com/NLPIR-team/NLPIR

Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Subscriptions: Thousands of  Big Data Experts
GitHub：https://github.com/NLPIR-team/NLPIR

 
发件人： xifengy
发送时间： 2021-01-28 19:55
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] 请问NLPIR 授权请求服务器的端口是多少？ (#201)
由于我的服务器部署在内网中，所有对外的网络请求都是默认受限的，需要访问外部资源需要在防火墙上开通。
例如要访问外部某webservice； http://xxxxx:8120/xxxx.asmx，则需要开通对应的端口8120的访问权限。
NLPIR 在进行授权验证时，由于向外网进行请求身份认证，而被防火墙拦截，因此一直提示验证失败。
请问NLPIR 授权验证的目标端口是多少？ 只需要端口即可， 谢谢！
