### ISSUE TITLE
老师您好，授权文件过期了，麻烦更新下，非常感谢！

### ISSUE THREAD

**Issue by Makefile123** [NLPIR-team/NLPIR#217]

**Comment by 18381305006** [comment]
收到，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NLPIR-team/NLPIR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 上午9:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[NLPIR-team/NLPIR] 老师您好，授权文件过期了，麻烦更新下，非常感谢！ (#217)
