### ISSUE TITLE
关于用

### ISSUE THREAD

**Issue by kushayaner** [NLPIR-team/NLPIR#218]

**Comment by kushayaner** [comment]
请问用用java跑sentimentnew组件，分析一篇研究报告，结果中出现的  <polarity>
</postivepoint>   <negtivepoint>，各自的数值计算原理是什么，想用情感分析写一篇文章，希望不吝赐教，特别感谢

**Comment by kushayaner** [comment]
请问用用java跑sentimentnew组件，分析一篇研究报告，结果中出现的 <polarity> </postivepoint> . <negtivepoint>  

，各自的数值计算原理是什么，想用情感分析写一篇文章，希望不吝赐教，特别感谢

**Comment by yangyaofei** [comment]
https://github.com/NLPIR-team/NLPIR/tree/master/paper
