### ISSUE TITLE
License文件失效

### ISSUE THREAD

**Issue by jiashuncheng** [NLPIR-team/NLPIR#221]

**Comment by jiashuncheng** [comment]
License文件夹中最新的是3个月之前的，感谢更新一下

**Comment by zhaoxun123** [comment]
nlpir.user 是三个月之前的 感谢更新一下

**Comment by 362294181** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
