### ISSUE TITLE
Sentiment Analysis初始化失败

### ISSUE THREAD

**Issue by tomorrow1pan** [NLPIR-team/NLPIR#25]
请教各位大神，我按照Sentiment Analysis情感分析组件使用手册运行结果显示：
windows 7
amd64
SentimentAnalysis初始化失败
[2016-08-19 17:22:48] License file sentimentAnalysisData\Data\sentiment.user can not open!
Cannot write log file sentimentAnalysisData\20160819.err!
请问这是什么原因？授权失败吗？该怎样解决呢？希望各位大神不吝指教！！

**Comment by tomorrow1pan** [comment]
求大神帮忙！！！

**Comment by tomorrow1pan** [comment]
哦哦，自己清楚了，打扰了

**Comment by FinalAgito** [comment]
等等，我也是这个原因啊！想问问是怎么解决的？

**Comment by FinalAgito** [comment]
我改变了路径，结果还是失败...也没有提示..好奇怪

**Comment by yw411** [comment]
同问，怎么解决的呀？

**Comment by tomorrow1pan** [comment]
你好，问题可能在于路径不对，报错说“sentimentAnalysisData\Data\sentiment.user”，而我之前是直接把Data这个文件夹复制到根目录下的，应该是把Data文件夹上一层文件夹sentimentAnalysisData整体复制到Test根目录下，这样就解决了，而且要定期更新证书，别许可证过期了。
我的问题是这样解决的，希望可以帮助到你

**Comment by yw411** [comment]
@tomorrow1pan ，非常感谢，解决了，是证书过期了，sentiment.user和NLPIR.user都要更新才可。
