### ISSUE TITLE
SentimentAnalysis情感分析返回结果都是0

### ISSUE THREAD

**Issue by complexly** [NLPIR-team/NLPIR#27]
使用LJSentimentAnalysis情感分析返回结果都是0

查看了以往issue，是否需要更新对应的数据？

此外，SentimentAnalysis使用ImportUserDict载入词典后，是与原有模型一起起作用吗？谢谢！

**Comment by Dr-Kevin-Zhang** [comment]
应该是词典路径设置的问题，没有正确的读取系统内的情感词典，导入的词典会跟原来的模型一起起作用的。
