### ISSUE TITLE
又是sentimentAnalysis授权失效

### ISSUE THREAD

**Issue by kevinswiss** [NLPIR-team/NLPIR#3]
大家好，又出现了之前的那个问题。

使用最新版的sentiment.user文本提示““License file Data\sentiment.user can not open!””，使用历史版本中的sentiment.user则提示"Not valid license or your license expired! Please feel free to contact the author!"

是否又需要更新license文件？我是2015年9月18日测试的，得到了上面的结果。
期待您的回答。谢谢！

**Comment by huoshan12345** [comment]
sentimentAnalysis的授权不是sentiment.user，而是sentimentAnalysis.user

**Comment by kevinswiss** [comment]
谢谢您的回复，请问哪里可以获得到sentimentAnalysis.user的授权文件呢？

**Comment by kevinswiss** [comment]
尝试了别的功能，下载最新的授权文件后，都是显示"Can not open License file"，请给予帮助，谢谢。

**Comment by huoshan12345** [comment]
不好意思，我弄错了。
sentimentAnalysis的授权文件也是sentiment.user
估计是sentiment.user已经过期，我联系一下我们的维护人员升级一下。

如果是SentimentNew这个组件的话，它的授权文件应该是NLPIR.user

**Comment by huoshan12345** [comment]
授权已经更新
