### ISSUE TITLE
sentiment.user文件无法打开

### ISSUE THREAD

**Issue by yanggeorge** [NLPIR-team/NLPIR#4]
使用最新的sentiment.user文件出现如下错误：
License file sentimentAnalysisData\Data\sentiment.user can not open!
而使用大数据论坛上的sentiment授权文件出现错误为：
Not valid license or your license expired! Please feel free to contact the author!

所以，应该不是授权文件没有找到的问题吧。另外我也已经尝试吧Data文件移到根目录，仍然是无法打开的错误。

**Comment by Dr-Kevin-Zhang** [comment]
访问 https://github.com/NLPIR-team/NLPIR/tree/master/License/Sentiment%E6%83%85%E6%84%9F%E5%88%86%E6%9E%90%E6%8E%88%E6%9D%83  下载吧。




Best wishes
张华平 博士 副教授 研究生导师
北理工大数据搜索挖掘实验室 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
博客:http://hi.baidu.com/drkevinzhang/
微博:http://www.weibo.com/drkevinzhang/
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab.
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Blog:http://hi.baidu.com/drkevinzhang/
Twitter: http://www.weibo.com/drkevinzhang/
 
发件人： yanggeorge
发送时间： 2015-10-06 16:35
收件人： NLPIR-team/NLPIR
主题： [NLPIR] sentiment.user文件无法打开 (#4)
使用最新的sentiment.user文件出现如下错误：
License file sentimentAnalysisData\Data\sentiment.user can not open!
而使用大数据论坛上的sentiment授权文件出现错误为：
Not valid license or your license expired! Please feel free to contact the author!
所以，应该不是授权文件没有找到的问题吧。另外我也已经尝试吧Data文件移到根目录，仍然是无法打开的错误。

**Comment by yanggeorge** [comment]
谢谢，之前git clone下载出错了。
