### ISSUE TITLE
请问4月份NLPIR-ICTCLAS分词授权什么时候更新啊？

### ISSUE THREAD

**Issue by jxcdut** [NLPIR-team/NLPIR#48]

**Comment by lixiaomeng8520** [comment]
就是啊，什么时候更新啊

**Comment by SUTLFen** [comment]
求授权文件！

**Comment by hanhan4321** [comment]
I use pynlpir update to update the license,it also has the the same error:
pynlpir.LicenseError: Your license appears to have expired. Try running "pynlpir update".
then I debug it ,find it in init.py

elif 'Can not open License file' in line:
raise LicenseError('Your license appears to be '
'missing. Try running "pynlpir '
'update".')

I tried many times,I don't know the reason.

**Comment by jxcdut** [comment]
更新了！license updated！
