### ISSUE TITLE
要怎么用正确的方式下载单个的授权文件呢？

### ISSUE THREAD

**Issue by jokertail** [NLPIR-team/NLPIR#61]
用浏览器直接下载的授权文件，依然会遇到初始化失败的问题，那么应该是下载的方式不对吧，那么正确的下载方式是怎样的呢？还有，为什么下载方式的不同会造成这样的问题呢？

**Comment by phylieac** [comment]
使用svn命令或者在github上点开相应的授权文件，点RAW或者打开另存为

**Comment by yuanyuan0066** [comment]
为什么点开单个授权文件在平台上显示都是乱码呢？

**Comment by phylieac** [comment]
没关系，另存为.user文件即可
