### ISSUE TITLE
mac平台的下载链接在哪里？

### ISSUE THREAD

**Issue by xixiaoyao** [NLPIR-team/NLPIR#62]
好混乱。官网给出的链接是错误的，怎么链接到了github的liscense？
```
ICTCLAS2016 发布了 IOS X下的开发包，在Android之外，我们也可以在MacBook, iPhone使用我们实验室包括分词在内的各类大数据搜索与挖掘工具了。下载地址： https://github.com/NLPIR-team/NLPIR/tree/master/License
```
github上的readme也好混乱，完全没有看懂mac版如何下载如何使用。
在官网上下载下来的压缩包全是乱码，文件名都是乱码，文本文档完全打不开，提示编码未知。多次尝试都是这样。对mac操作系统很不友好啊

**Comment by phylieac** [comment]
https://github.com/NLPIR-team/NLPIR/tree/master/NLPIR%20SDK/NLPIR-ICTCLAS/lib/ios,修改后缀为dylib

**Comment by xixiaoyao** [comment]
谢谢！
