### ISSUE TITLE
关键词提取组件不可用

### ISSUE THREAD

**Issue by ghost** [NLPIR-team/NLPIR#70]
您好，我在今天使用您的关键词提取组件的时候，更新为最新的授权文件，但是仍然提示：Not valid license or your license expired! Please feel free to contact the author

**Comment by WhiteFoxLYJ** [comment]
I have the same problem that the keyextractor not work.

**Comment by Dr-Kevin-Zhang** [comment]
替换应该可以。



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： 5347964
发送时间： 2017-08-24 12:29
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] 关键词提取组件不可用 (#70)
您好，我在今天使用您的关键词提取组件的时候，更新为最新的授权文件，但是仍然提示：Not valid license or your license expired! Please feel free to contact the author

**Comment by WhiteFoxLYJ** [comment]
您好，我在今天尝试关键词组件的时候发现授权过期。
测试其他组件，只有DocExtractor可以正常使用。已经替换过了授权文件，但是仍然显示无法使用。
是否为github上的授权文件已经过期，需要再次更新。

**Comment by 5347964** [comment]
@WhiteFoxLYJ 我试了一下，发现我这个DocExtractor也不能用，^_^; 全部是最新的授权文件

**Comment by WhiteFoxLYJ** [comment]
@5347964 授权文件已更新，可以试试。

**Comment by WhiteFoxLYJ** [comment]
@Dr-Kevin-Zhang 谢谢您的及时回复。

**Comment by 5347964** [comment]
@Dr-Kevin-Zhang 感谢，给您添麻烦了。
