### ISSUE TITLE
组件不能使用

### ISSUE THREAD

**Issue by WhiteFoxLYJ** [NLPIR-team/NLPIR#78]
所有的组件都不能使用了，应该是用户授权过期了，能否将授权文件更新一下，谢谢！

**Comment by WhiteFoxLYJ** [comment]
我已经更新到了今天最新的授权文件，但是还是不能使用。
报错：Exception in thread "main" java.lang.Error: Invalid memory access

**Comment by WhiteFoxLYJ** [comment]
看到授权文件中 NLPIR.user 是两个月之前的文件了，是否是这个授权文件影响其他所有的授权文件的使用呢？

**Comment by Dr-Kevin-Zhang** [comment]
已经更新了授权，谢谢你的使用。



Best wishes
张华平 博士 副教授 研究生导师
大数据搜索挖掘实验室（北京市海量语言信息处理与云计算应用工程技术研究中心） 主任
地址：北京海淀区中关村南大街5号 100081
电话：+86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
网站: http://www.nlpir.org (自然语言处理与信息检索共享平台)
http://www.bigdataBBS.com (大数据论坛)
微博:http://www.weibo.com/drkevinzhang/
微信：drkevinzhang
微信公众号：大数据千人会
Dr. Kevin Zhang  (张华平，Zhang Hua-Ping)
Associate Professor, Graduate Supervisor
Director, Big Data Search and Mining Lab. 
Beijing Engineering Research Center of Massive Language Information Processing and Cloud Computing Application
Beijing Institute of Technology
Add: No.5, South St.,Zhongguancun,Haidian District,Beijing,P.R.C  PC:100081
Tel: +86-10-68918642
Email:kevinzhang@bit.edu.cn
MSN:  pipy_zhang@msn.com;
Website: http://www.nlpir.org (Natural Language Processing and
Information Retrieval Sharing Platform)
http://www.bigdataBBS.com (Big Data Forum)
Twitter: http://www.weibo.com/drkevinzhang/
Webchat: drkevinzhang
Subscriptions: Thousands of  Big Data Experts
 
发件人： WhiteFoxLYJ
发送时间： 2017-09-26 13:54
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： [NLPIR-team/NLPIR] 组件不能使用 (#78)
所有的组件都不能使用了，应该是用户授权过期了，能否将授权文件更新一下，谢谢！

**Comment by Dr-Kevin-Zhang** [comment]
不影响
 
发件人： WhiteFoxLYJ
发送时间： 2017-09-26 17:46
收件人： NLPIR-team/NLPIR
抄送： Subscribed
主题： Re: [NLPIR-team/NLPIR] 组件不能使用 (#78)
看到授权文件中 NLPIR.user 是两个月之前的文件了，是否是这个授权文件影响其他所有的授权文件的使用呢？

**Comment by WhiteFoxLYJ** [comment]
不好意思，是我测试的方法写错了，麻烦您了 @Dr-Kevin-Zhang
