### ISSUE TITLE
从GitHub下载太慢，不知能否提供网盘等其他下载渠道

### ISSUE THREAD

**Issue by yaleimeng** [NLPIR-team/NLPIR#88]
作为分流下载途径。

**Comment by Devil502177243** [comment]
http://ictclas.nlpir.org/downloads  下载Data文件的地址

**Comment by yaleimeng** [comment]
@Devil502177243  官网的下载链接都是很久以前的。2017年那个分词系统只有72MB，不是项目本身。这个项目rar包有636MB。    
不过好在旁边公司网速快，已经下载到了。
回头我上传到网盘上，给需要的人分流。然后关闭此Issue。

**Comment by yaleimeng** [comment]
如有需要，请移步链接：http://pan.baidu.com/s/1jImsKHS 密码：coga

**Comment by IRISRRY** [comment]
nn

> 如有需要，请移步链接：http://pan.baidu.com/s/1jImsKHS 密码：coga

您好，可以再分享一次网盘吗？这个文件取消了

**Comment by yaleimeng** [comment]
文件被百度禁止分享了。重新分享要等我下载下载下来之后上传到别的平台。请稍等更新……@IRISRRY  
另外：当时分享的包是三年前的，项目后续的更新都不能享受到。最新的项目，我从GitHub也很难下载下载，正在缓慢SVN下载……
另外：我们当初试了一下之后就没有再用这个库了，如果不是非要用的话建议选择其他开源库。
