### ISSUE TITLE
分词证书过期

### ISSUE THREAD

**Issue by DJJune** [NLPIR-team/NLPIR#91]
分词证书已经超过1个月了，是不是已经过期了，现在没办法使用

**Comment by zkdgh** [comment]
分词什么时候过期...就这个一个多月没更新了，不会突然不可用吧

**Comment by DJJune** [comment]
我下载了现在最新版的证书，但还是报错了
pynlpir.LicenseError: Your license appears to have expired. Try running "pynlpir update".
