### ISSUE TITLE
急求！！SentimentAnalysis授权过期了，求是否会更新

### ISSUE THREAD

**Issue by folinhuakai** [NLPIR-team/NLPIR#99]
GitHub上的授权文件显示是26天前更新的，为什么运行结果收是授权失败，而且授权文件没什么问题，大小是3点多mb呀

**Comment by pengqiuyuan** [comment]
+1

**Comment by pengqiuyuan** [comment]
@Dr-Kevin-Zhang  张老师

**Comment by qiufengyu** [comment]
keyextractor 好像也过期了，求更新！

**Comment by Dr-Kevin-Zhang** [comment]
已经更新过了

 
发件人： pengqiuyuan
发送时间： 2018-01-23 17:13
收件人： NLPIR-team/NLPIR
抄送： Dr. Kevin Zhang; Mention
主题： Re: [NLPIR-team/NLPIR] 急求！！SentimentAnalysis授权过期了，求是否会更新 (#99)
@Dr-Kevin-Zhang 张老师

**Comment by qiufengyu** [comment]
哇，谢谢张老师！很及时！

**Comment by folinhuakai** [comment]
感谢！
